config/routes.rb
Rails.application.routes.draw do
  get 'quotes/index'
  get 'quotes/new'

  root to: 'quotes#index' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :quotes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
	validates :text, presence: true
	validates :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
  	@quote = Quote.all
  	@quote = Quote.paginate(:page => params[:page], :per_page => 12)
  end

  def show
  	@quote = Quote.find(params[:id])
  end

  def new
  		@quote = Quote.new
  end
  def create
  	@quote = Quote.new(quote_params)

  	if(@quote.save)
  		redirect_to root_path
  	else 
  		render 'new'
  	end
  end

  private def quote_params
  	params.require(:quote).permit(:text,:author)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quoter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-success navbar-fixed-top">
      <%= link_to 'QuoteGenerator', root_path, {:class => "nav-link navbar-brand text-light"} %>
    </nav>
    <div class="container">
       <%= yield %>
    </div>
   
  </body>
</html>

app/views/quotes/index.html.erb
<h1 class="text-center pt-5">Quote list</h1>
<%= link_to "Add quote", new_quote_path, {:class => 'btn btn-success'}%>
<ul class="list-group pt-2">
<% @quote.each do |quote| %>
	<li class="list-group-item">
		<p class="lead"><%= quote.text %></p>
		<p><%= quote.author %></p>
		<p><%= quote.created_at.strftime('%d %B %Y') %></p>
	</li>
	
<% end %>
</ul>
<%= will_paginate @quote, ({:class => 'text-center pt-2'}) %>

app/views/quotes/new.html.erb
<h1 class="pt-5 text-center">Add quote</h1>
<%= form_for :quote, url: quotes_path do |f| %>
  <% if @quote.errors.any? %>
    <% @quote.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
	<p>
   <%= f.label :text %>
   <%= f.text_field :text, {:class => 'form-control'} %> 
  </p>
  <p>
    <%= f.label :author %>
    <%= f.text_field :author, {:class => 'form-control'} %>
  </p>

  <%= f.submit ({:class => 'btn btn-success'}) %>
   
  <% end %>

app/views/quotes/show.html.erb
<h2><%= @quote.text %></h2>
<p><%= @quote.author%></p>